### PR TITLE
fix (template-link): update-link - issue #171

### PR DESCRIPTION
**Pull request by doomswatter**
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>

# Issue #171
Replaced link to old version of template with link to current version.

### Changes
- Replaced link to old version of template with link to current version.

### Flags
- 

### Related Issues
- Issue #171

### CODE REVIEW

**Comment by irmerk** [comment]
Not sure how this relates t o #171

**Comment by doomswatter** [comment]
Ah, I added the issue without thinking because I was in the middle of working on it when I submitted this PR. The PR is still good, I think, but it is a separate issue.

**Comment by irmerk** [comment]
@jeromesimeon I think you're right, I didn't catch that #194 is using `0.2.1`. So we should go back and redo #194 but with `0.4.0`, correct?

**Comment by doomswatter** [comment]
No, the images replaced in #194, to correct the incorrect order or "buyer" and "seller", were late2, late3, late4, late10, late11, and late12. All of those were shot from version 0.4.0, which is the only version I could access anyway. It's not apparent in all of them, but you can see 0.4.0 in late2 and late12.

The screenshots still showing 0.2.1 are shots that did not need to be corrected for this particular issue.

**Pull request closed without merging**
