### PR TITLE
Issue#275

### LINKED ISSUE #275: Diagram Contract Model
We should capture this diagram, or one like it, in our documentation. This is from our slide deck template.

Screen Shot 2020-03-05 at 8 45 55 AM

### PR DESCRIPTION
**Pull request by somnathPrasad**
# Closes #275 

### Changes

- Added Concepts and High-level Architecture file in the docs under Template guides section

### Screenshots or Video

Screenshot 2021-06-24 204735

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:issue#275`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by mttrbrts — APPROVED** [review]
Apologies for the delay in getting to this @somnathPrasad. Can you sign the DCO and we can get this merged?

**Comment by somnathPrasad** [comment]
DCO

Signed-off-by: Somnath Prasad <somnathprasad559@gmail.com>

**Comment by somnathPrasad** [comment]
remote: Permission to accordproject/techdocs.git denied to somnathPrasad.
fatal: unable to access 'https://github.com/accordproject/techdocs.git/': The requested URL returned error: 403

**Comment by somnathPrasad** [comment]
@mttrbrts can you help with this ☝️

**Comment by mttrbrts** [comment]
> @mttrbrts can you help with this ☝️
> 

I'll figure out the deployment failure.

You can fix the DCO signoff online here, https://github.com/accordproject/techdocs/runs/2906241758

**Comment by somnathPrasad** [comment]
yes that link is also saying to do this

git push --force-with-lease origin issue#275

but i am getting the same error: access denied

**Pull request closed without merging**
