### PR TITLE
docs(README): add custom accord project badge - I81

### PR DESCRIPTION
**Pull request by michizhou**
Signed-off-by: Michael Zhou <myz227@nyu.edu>

# Issue #81 
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
- Added custom Accord Project badge for use in Accord Project repositories 
  - Badge displays "Accord Project" name with current version number

### Flags
- Subject to review with potential badge design changes possibly needed

### CODE REVIEW

**Comment by irmerk** [comment]
Hoping for input by the reviewers. @peterhunn is out until the 22nd, would especially like his input.

**Comment by Michael-Grover** [comment]
@michizhou can you send screenshots of these badges? I'm not sure how to preview it

**Comment by irmerk** [comment]
@Michael-Grover https://github.com/michizhou/techdocs/tree/michizhou-issue81-badge-creation

**Comment by irmerk** [comment]
> Why is the "contributors" badge square?

I believe the square aspect is from https://github.com/accordproject/techdocs/pull/162

> The issue referenced (#81 ) seems to refer to an badge for the Accord Project slack, which makes more sense to me.

I think I made it with a unified AP version in mind, basically when we synced up versions in `v.013`

**Comment by Michael-Grover** [comment]
lgtm except the square corners look out of place

**Comment by irmerk** [comment]
> lgtm except the square corners look out of place
> I believe the square aspect is from #162

@Michael-Grover I don't think that's an issue with this PR. I think there should also be consideration around how we present this to those who may want to display it in their own README's.

**Comment by dselman** [comment]
Does this mean that every time we release new code we are going to have to update a badge and then update dozens of README files?

**Comment by irmerk** [comment]
> Does this mean that every time we release new code we are going to have to update a badge and then update dozens of README files?

I think the original idea was to implement something similar to how `npm package` badges are linked to automatically be in sync with the version. So the badge would have a link to the docs, maybe.

**Comment by jeromesimeon** [comment]
> > Why is the "contributors" badge square?
> 
> I believe the square aspect is from #162
> 

Why is the badge from #162 square?

> > The issue referenced (#81 ) seems to refer to an badge for the Accord Project slack, which makes more sense to me.
> 
> I think I made it with a unified AP version in mind, basically when we synced up versions in `v.013`

Having an Accord Project badge for people who _use_ accord project technology (e.g., to embed in repos for user-defined templates) would make sense to me. e.g., this could point to Cicero. I find this badge particularly confusing in the context of individual AP repos themselves. (also we are starting to have too many badges which make the really useful ones (such as package version, build and coverage info) harder to see.

**Comment by irmerk** [comment]
Closing for now, refer to #81

**Pull request closed without merging**
