### PR TITLE
center logo of Accord Project in readme

### PR DESCRIPTION
**Pull request by DEBSUBHRO**
# Issue #79 
<OVERALL SUMMARY OF PULL REQUEST>

### Changes
Centering the logo of Accord Project.

### Related Issues
- Issue #79 
- Pull Request #105

### CODE REVIEW

**Comment by irmerk** [comment]
Thanks for the PR! I like the `h1` so it has a `hr` below it. You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by DEBSUBHRO** [comment]
> Thanks for the PR! I like the `h1` so it has a `hr` below it. You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> 
> > Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

Okay ma'am.

**Comment by DEBSUBHRO** [comment]
Ma'am, I will need some time to add a DCO (Developers Certificate of Originality) because I need to set my git on computer. 
Thank you.

**Comment by DEBSUBHRO** [comment]
> Thanks for the PR! I like the `h1` so it has a `hr` below it. You'll want to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> 
> > Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

Ma'am I have pulled a new request #125. Please check it.

**Pull request closed without merging**
