### PR TITLE
Updated alt text for images on the home page

### PR DESCRIPTION
**Pull request by Alexandria**
# Issue #113 
Updated Alt text for images on the home page
### Changes
- Added alt text to each image
### Flags
- none

### Related Issues
- Issue #113 
- Pull Request N/A

### CODE REVIEW

**Comment by Alexandria** [comment]
> @Alexandria the alt text you added on the homepage looks great, thank you. Very descriptive.
> 
> It looks like your PR failed the DCO signoff check.
> 
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see here
> 
> https://github.com/probot/dco#how-it-works

Gotcha! Everything should be good now.

**Comment by Michael-Grover** [comment]
@Alexandria thanks. Did you find any leads about how to add alt text to interior pages such as this one? There must be a way since some of them have alt text. 

@jeromesimeon Do you know how alt text is added to images like this?

image

**Comment by Michael-Grover** [comment]
Thanks again @Alexandria ! If you have any ideas about alt text on interior pages let me know.

**Comment by Alexandria** [comment]
> Thanks again @Alexandria ! If you have any ideas about alt text on interior pages let me know.

I plan to start working on those next! I should have an update in a day or two.

**Pull request merged**
