### PR TITLE
A11y text

### PR DESCRIPTION
**Pull request by Alexandria**
# Issue #113 
Added alt text for the following pages:
- [x] /accordproject.html 
- [x] /accordproject-tooling.html 
### Changes
Updated the alt descriptions for images 
### Flags
- N/A
### Related Issues
- Issue #113 
- Pull Request N/A

### CODE REVIEW

**Comment by Alexandria** [comment]
> Thanks for the PR. I think these alt text attributes are too long overall. I've read the ideal alt text is 125 characters. One way to shorten these is to not include information in the alt text that is repeated elsewhere in the actual text. My understanding is the alt text should only describe information that the image conveys but the surrounding text does not.
> 
> For example this:
> 
> A block of code that is a “contract”. Within the contract there is another block of code that is a “clause”. The clause contains a variable called status and returns a new instance of the InspectionResponse object.
> 
> Can be come this: "Visual Studio Code running the Accord Project plugin"
> 
> And this:
> [An example of a .tem file. There are 3 paragraphs of a contract with binding variables incorporated in each paragraph]
> 
> Can become this: "A template being edited in Template Studio."

Gotcha! Thanks for the feed back. I was teetering back and forwards between interpreting these images as a graph that has information that needs more detail or simply an image conveying a high level point.  This clears things up a lot!

**Comment by Michael-Grover** [comment]
@Alexandria this PR looks messy with all the other commits, how do I see only the changes you made?

**Comment by irmerk** [comment]
@Alexandria I think you'll want to interactive rebase to cleanup the commits.

**Comment by jeromesimeon** [comment]
@irmerk @Alexandria Lots of useful fixes in there, it would be a shame to lose it? Maybe it would be easier to re-apply on the latest version? Any opinion on what to do with this PR?

**Comment by irmerk** [comment]
Closing, if you come back to it @Alexandria just start from an updated master.

**Pull request closed without merging**
