### PR TITLE
docs(README): include docusaurus link

### PR DESCRIPTION
**Pull request by pratikbutani**
Signed-off-by: Pratik Butani pratik13butani@gmail.com

### CODE REVIEW

**Comment by irmerk** [comment]
Thanks for the PR! You'll want to make sure to add a DCO (Developers Certificate of Originality) per [the instructions](https://github.com/accordproject/models/blob/master/CONTRIBUTING.md):
> Ensure you provide a DCO sign-off for your commits using the -s option of git commit. For more information see [how this works](https://github.com/probot/dco#how-it-works).

**Comment by jeromesimeon** [comment]
@pratikbutani Any progress on this?

**Comment by pratikbutani** [comment]
> @pratikbutani Any progress on this?

I am not getting how to resolve it. Can you please suggest.

**Comment by irmerk** [comment]
You'll want to amend the commits with `git commit --amend --signoff` and then force push.

**Comment by pratikbutani** [comment]
> git commit --amend --signoff

S I have to commit from cmd, will it not work directly on GitHub?

**Comment by irmerk** [comment]
I'm not as familiar with GitHub Desktop, but I don't believe you can do it on there. I'd recommend using the CLI going forward.

**Comment by jeromesimeon** [comment]
No activity on this. I'm folding the fix into https://github.com/accordproject/techdocs/pull/198

**Pull request closed without merging**
