### PR TITLE
change pictures for advanced-latedelivery.md

### LINKED ISSUE #171: advanced-latedelivery.md: Buyer and Seller must be swapped
**Is your feature request related to a problem? Please describe.**
'Buyer' and 'Seller' in this documentation must be swapped (seller must pay buyer, not the other way around) 

**Describe the solution you'd like**
As above - both in the text and in the image files

**Describe alternatives you've considered**
N/A

**Additional context**
Potentially linked to [Cicero Template Library Issue #259](https://github.com/accordproject/cicero-template-library/issues/259 )

### PR DESCRIPTION
**Pull request by daniloff200**
Signed-off-by: Dmitry Danilov <daniloff200@gmail.com>

# Issue #171 
<OVERALL SUMMARY OF PULL REQUEST>

Well, my previous PR was merged, but, there were only text changes, and I wasn't able to add new pictures, with updated version & contract content. 
This PR adds new images

 
### Related Issues
 - Pull Request #174 

should finally close #171 

@4katie  can you review that please? 

P.S. 
Here's the link to changed file: https://github.com/daniloff200/techdocs/blob/fix-latedelivery-pics/docs/advanced-latedelivery.md

### CODE REVIEW

**Comment by daniloff200** [comment]
@irmerk that's probably because previous screens was made from MacOS, and I'm a poor boy, who use Linux Mint :rofl:

**Comment by irmerk** [comment]
I think I'd rather have these with monospace to denote code - @jeromesimeon and @Michael-Grover thoughts?

**Comment by Michael-Grover** [comment]
Yeah I agree monospace is preferable

**Comment by daniloff200** [comment]
Yeah, okay, let's close this one them, because, there's no option for me to fix the issue with fonts

cc @irmerk  you can assign it to someone else them

**Comment by jeromesimeon** [comment]
> Yeah, okay, let's close this one them, because, there's no option for me to fix the issue with fonts
> 
> cc @irmerk you can assign it to someone else them

@daniloff200 did you try an use template studio itself? Was there any issue with taking that route?

**Comment by daniloff200** [comment]
@jeromesimeon  yeah, I've made screens from https://studio.accordproject.org/

**Pull request closed without merging**
