### PR TITLE
(fix) Changes in dark backgrounds

### PR DESCRIPTION
**Pull request by javiercanossini**
Signed-off-by: Javier Canossini <javier@ingamana.com>

### CODE REVIEW

**Comment by mttrbrts** [comment]
@Michael-Grover are you happy with this?

**Comment by Michael-Grover** [comment]
@mttrbrts @javiercanossini is there some way I can check this? What is this change? It doesn't look like anything substantial that I would be worried about.

**Comment by mttrbrts** [comment]
If you click 'show all checks' then click 'Details' next to the netlify check, you get a preview.
image

**Comment by Michael-Grover** [comment]
@mttrbrts oh I see. This accordion is automatically expanded in other repos, so I didn't notice Netlify was here.

**Comment by Michael-Grover** [comment]
@mttrbrts it looks good to me

**Pull request merged**
