### PR TITLE
docs(TemplateGuides):correct typo in TemplateGuides - #391

### LINKED ISSUE #391: Spelling error in templateGuides/preliminaries.
# Bug Report 🐛

There is spelling error in TemplateGuides/preliminaries. BlockName is misspelled as BlockBane.
issue1

### PR DESCRIPTION
**Pull request by amanag25**
Signed-off-by: aman <amanvivoy51l@gmail.com>

# Closes #391 

### Changes

- Change in TemplateGuides/preliminaries- changed blockBane to blockName

### Screenshots or Video

issue

### Related Issues
- Issue #391 

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by irmerk — CHANGES_REQUESTED** [review]
I think the change should be made in this file: `https://github.com/accordproject/techdocs/blob/master/docs/markup-preliminaries.md`

The `website/versioned_docs/...` are not the source of truth, they're the previous versions of the file I listed above.

**Comment by amanag25** [comment]
ok I will update them accordingly. Thankyou for helping @irmerk

**Comment by irmerk** [comment]
Can you condense this down to only one commit?

**Comment by amanag25** [comment]
> Can you condense this down to only one commit?

Done @irmerk

**Review by irmerk — APPROVED** [review]

**Pull request merged**
