### PR TITLE
Replace "Cicero" and "Ergo" headers with logos

### PR DESCRIPTION
**Pull request by lex111**
# Issue #112

### Changes
Replace "Cicero" and "Ergo" headers with logos

Note: `website/static/img/ergo-logo.svg` was not used anywhere, so I replaced the content with a new one.

### CODE REVIEW

**Comment by jeromesimeon** [comment]
I'm happy to see that it seems possible. It doesn't look quite right though? @Michael-Grover 

Screenshot 2019-10-03 at 3 34 59 PM

**Comment by Michael-Grover** [comment]
@lex111 thank you, this is very close! Can you make the size of the logos match the mockup I provided in the issue? 

image

**Comment by lex111** [comment]
@Michael-Grover  via CSS?

**Comment by Michael-Grover** [comment]
@lex111 I'm not a dev so I can't say what the best way to resize these would be, but CSS makes sense to me. Ideally the top of all of the paragraphs should be aligned. It looks like in this PR the logos are pushing the first two paragraphs down.

**Comment by lex111** [comment]
@Michael-Grover done! :heavy_check_mark:

**Pull request merged**
